# Generated by Django 5.2.4 on 2025-09-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_guest_email_order_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
